[package]
name = "rsfetch"
version = "0.1.0"
authors = ["Huy Tran <kingbazoka@gmail.com>"]

[dependencies]
libc = "*"
serde_json = "*"
hyper = "*"
hyper-native-tls = "*"

[lib]
name = "rsfetch"
crate-type = ["dylib"]
